/// Flutter icons TswiriIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TswiriIcons
///      fonts:
///       - asset: fonts/TswiriIcons.ttf
///
/// 
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class TswiriIcons {
  TswiriIcons._();

  static const _kFontFam = 'TswiriIcons';
  static const String? _kFontPkg = null;

  static const IconData box = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drawer = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_full = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
